version: '3.8'
services:
  mongo_db:
    image: mongo:latest
    container_name: pametni_paketnik_name_db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO-ROOT-PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INIT-DB}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data: